{"url": "http://gis.vgsi.com/"}
{"url": "http://gis.vgsi.com/abingtonma/"}
{"url": "http://gis.vgsi.com/berlinct/"}
{"url": "http://gis.vgsi.com/biddefordme/Parcel.aspx?pid=6402"}
{"url": "http://gis.vgsi.com/branfordct/"}
{"url": "https://gis.vgsi.com/CharlestownRI/"}
{"url": "http://gis.vgsi.com/ChesterNH/"}
{"url": "http://gis.vgsi.com/clintonct/Parcel.aspx?pid=5345"}
{"url": "http://gis.vgsi.com/concordnh/"}
{"url": "http://gis.vgsi.com/concordnh/login.aspx"}
{"url": "http://gis.vgsi.com/CranstonRI/"}
{"url": "http://gis.vgsi.com/CranstonRI/Parcel.aspx?pid=8939"}
{"url": "http://gis.vgsi.com/deepriverct/"}
{"url": "http://gis.vgsi.com/derrynh/"}
{"url": "http://gis.vgsi.com/dracutma/"}
{"url": "http://gis.vgsi.com/dudleyma/Parcel.aspx?pid=100431"}
{"url": "http://gis.vgsi.com/eastprovidenceri/"}
{"url": "http://gis.vgsi.com/eastprovidenceri/Parcel.aspx?Pid=12249"}
{"url": "http://gis.vgsi.com/EastProvidenceRI/Search.aspx"}
{"url": "http://gis.vgsi.com/EllingtonCT/Parcel.aspx?pid=2144"}
{"url": "http://gis.vgsi.com/enfieldct/"}
{"url": "http://gis.vgsi.com/essexct/Sales.aspx"}
{"url": "http://gis.vgsi.com/exeternh/"}
{"url": "http://gis.vgsi.com/glastonburyct/"}
{"url": "http://gis.vgsi.com/greenecountypa/"}
{"url": "http://gis.vgsi.com/hamptonnh/Parcel.aspx?pid=1868"}
{"url": "http://gis.vgsi.com/HamptonNH/Search.aspx"}
{"url": "http://gis.vgsi.com/HollisNH/Parcel.aspx?pid=54"}
{"url": "http://gis.vgsi.com/hooksettnh/Parcel.aspx?pid=3559"}
{"url": "http://gis.vgsi.com/HooksettNH/Parcel.aspx?pid=4350"}
{"url": "http://gis.vgsi.com/KitteryME/"}
{"url": "http://gis.vgsi.com/laconianh/"}
{"url": "http://gis.vgsi.com/lexingtonma/"}
{"url": "http://gis.vgsi.com/LittleComptonRI/"}
{"url": "http://gis.vgsi.com/madisonct/"}
{"url": "http://gis.vgsi.com/MiddletownRI/"}
{"url": "http://gis.vgsi.com/MiddletownRI/"}
{"url": "http://gis.vgsi.com/MiddletownRI/"}
{"url": "http://gis.vgsi.com/MiddletownRI/"}
{"url": "http://gis.vgsi.com/MiddletownRI/Parcel.aspx?pid=269"}
{"url": "http://gis.vgsi.com/MoultonboroughNH/"}
{"url": "http://gis.vgsi.com/newbritainct/"}
{"url": "http://gis.vgsi.com/newportri/"}
{"url": "http://gis.vgsi.com/norfolkma/"}
{"url": "http://gis.vgsi.com/norfolkma/"}
{"url": "http://gis.vgsi.com/NorthYarmouthME/Parcel.aspx?pid=92"}
{"url": "http://gis.vgsi.com/NorwalkCT/"}
{"url": "http://gis.vgsi.com/NorwellMA/"}
{"url": "http://gis.vgsi.com/NorwichCT/"}
{"url": "http://gis.vgsi.com/oldsaybrookct/Parcel.aspx?Pid=4353"}
{"url": "http://gis.vgsi.com/portsmouthnh/"}
{"url": "http://gis.vgsi.com/providenceri/"}
{"url": "http://gis.vgsi.com/providenceri/Parcel.aspx?Pid=37302"}
{"url": "http://gis.vgsi.com/providenceri/Search.aspx"}
{"url": "http://gis.vgsi.com/putnamct/"}
{"url": "http://gis.vgsi.com/quincyma/"}
{"url": "http://gis.vgsi.com/RochesterMA/"}
{"url": "http://gis.vgsi.com/ryeny/"}
{"url": "http://gis.vgsi.com/SharonCT/"}
{"url": "http://gis.vgsi.com/smithfieldri/"}
{"url": "http://gis.vgsi.com/southbridgema/Default.aspx"}
{"url": "http://gis.vgsi.com/southbridgema/Default.aspx"}
{"url": "http://gis.vgsi.com/southwindsorct/"}
{"url": "http://gis.vgsi.com/stamfordct/"}
{"url": "http://gis.vgsi.com/stamfordct/Parcel.aspx?pid=12974"}
{"url": "http://gis.vgsi.com/stamfordct/Parcel.aspx?pid=25774"}
{"url": "http://gis.vgsi.com/stamfordct/Search.aspx"}
{"url": "http://gis.vgsi.com/strattonvt/"}
{"url": "http://gis.vgsi.com/sturbridgema/Parcel.aspx?pid=1069"}
{"url": "http://gis.vgsi.com/SuffieldCT/"}
{"url": "http://gis.vgsi.com/tewksburyma/"}
{"url": "http://gis.vgsi.com/tiogapa/"}
{"url": "http://gis.vgsi.com/trumbullct/"}
{"url": "http://gis.vgsi.com/WaylandMA/"}
{"url": "http://gis.vgsi.com/WaylandMA/Parcel.aspx?pid=3393"}
{"url": "http://gis.vgsi.com/wellsme/Parcel.aspx?pid=113073"}
{"url": "http://gis.vgsi.com/WesterlyRI/"}
{"url": "http://gis.vgsi.com/wilbrahamma/"}
{"url": "http://gis.vgsi.com/winchesterct/"}
{"url": "http://gis.vgsi.com/WinchesterCT/"}
{"url": "http://gis.vgsi.com/WindsorLocksCT/"}
{"url": "http://gis.vgsi.com/winthropma/"}
{"url": "http://gis.vgsi.com/woodbridgect/"}
{"url": "http://gis.vgsi.com/woonsocketri/"}
{"url": "http://gis.vgsi.com/woonsocketri/Parcel.aspx?pid=6968"}
{"url": "http://gis.vgsi.com/worcesterma/Parcel.aspx?pid=25163"}
{"url": "http://gis.vgsi.com/yarmouthma/Parcel.aspx?pid=9765"}
